### ISSUE TITLE
Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)

### ISSUE THREAD

**Issue by qingzew** [weiliu89/caffe#651]
Operating system: centos 6.3
Compiler: gcc4.64
CUDA version (if applicable):7.5
CUDNN version (if applicable):v5
BLAS:atlas

**Comment by tamnicer** [comment]
if the problem caused by memory, you can reduce the batch size.

**Comment by qingzew** [comment]
when I set batch_size = 1, it also turns out 
`619 13:48:49.090816 24023 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
`

**Comment by tamnicer** [comment]
did you change all the bath size of ssd_pascal.py? (339, 340 and 362 line?) how did you change that?

**Comment by qingzew** [comment]
@tamnicer @weiliu89 yes, i change all of them

**Comment by HansRen1024** [comment]
@qingzew did u solve this problem?

**Comment by HansRen1024** [comment]
I solved this problem by adding 	**engine: CAFFE**  under  **convolution_param**  in every convolution layers in train_val.prototxt

**Comment by robinloujun** [comment]
> I solved this problem by adding **engine: CAFFE** under **convolution_param** in every convolution layers in train_val.prototxt

Hi, may I ask how were you able to modify the prototxt? I find that the prototxt-s are created by the launch file like ssd_pascal.py

**Comment by robinloujun** [comment]
> I solved this problem by adding **engine: CAFFE** under **convolution_param** in every convolution layers in train_val.prototxt

@HandsomeHans  may I ask how did you modify the train_val.prototxt since they are created by the launch file like ssd_pascal.py?

**Comment by robinloujun** [comment]
I found the problem could be solved with clue from this [issue](https://github.com/weiliu89/caffe/issues/863#issuecomment-469534074), sorry for the bothering
